import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="fixed top-0 left-0 w-full h-full 
        bg-gradient-to-r from-transparent via-black via-45% to-transparent to-99%
        -z-10"
        ></div>
        <div
          className="fixed top-0 left-0 w-full h-full 
        bg-gradient-to-l from-transparent via-black via-45% to-transparent to-99%
        -z-10"
        ></div>
        <div className="fixed left-0 top-0 h-full w-1/2 heropattern-circuitboard-gray-500 -z-20 opacity-25"></div>
        <div className="fixed right-0 top-0 h-full w-1/2 heropattern-fallingtriangles-gray-500 -z-20 opacity-25"></div>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
